# Generated by Django 4.1.13 on 2025-02-21 05:31

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetails_Days',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('Student_id', models.CharField(max_length=25)),
                ('Subject', models.CharField(max_length=25)),
                ('Attempts', models.IntegerField()),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Score', models.FloatField()),
                ('Qn', models.TextField(max_length=25)),
                ('Ans', models.TextField()),
                ('Result', djongo.models.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Attendance',
            fields=[
                ('SLID', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.CharField(max_length=10000)),
                ('QnID', models.CharField(max_length=25)),
                ('Competency', models.CharField(max_length=25)),
                ('EnteredAnswer', models.CharField(max_length=25)),
                ('CorrectAnswer', models.CharField(max_length=25)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_UserDetails',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=25, unique=True)),
                ('College', models.CharField(max_length=25)),
                ('Branch', models.CharField(max_length=25)),
                ('Questions', djongo.models.fields.JSONField(default=list)),
                ('Questions_status', djongo.models.fields.JSONField(default=dict)),
                ('Coding_Questions', djongo.models.fields.JSONField(default=list)),
                ('Coding_Questions_status', djongo.models.fields.JSONField(default=dict)),
                ('Score', models.IntegerField(default=0)),
                ('Coding_Score', models.IntegerField(default=0)),
                ('Test_status', models.CharField(default='Not_Started', max_length=25)),
                ('Coding_Test_status', models.CharField(default='Not_Started', max_length=25)),
                ('Duration', models.IntegerField(default=0)),
                ('Last_update', models.DateTimeField(default=None)),
            ],
        ),
    ]
