# Generated by Django 4.1.13 on 2025-02-18 12:27

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Attendance',
            fields=[
                ('SLID', models.AutoField(primary_key=True, serialize=False)),
                ('UID', models.CharField(max_length=10000)),
                ('QnID', models.CharField(max_length=25)),
                ('Competency', models.CharField(max_length=25)),
                ('EnteredAnswer', models.CharField(max_length=25)),
                ('CorrectAnswer', models.CharField(max_length=25)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_UserDetails',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=25, unique=True)),
                ('Collage', models.CharField(max_length=25)),
                ('Branch', models.CharField(max_length=25)),
                ('Questions', djongo.models.fields.JSONField(default=list)),
                ('Questions_status', djongo.models.fields.JSONField(default=dict)),
                ('Score', models.IntegerField(default=0)),
            ],
        ),
    ]
