# Generated by Django 4.1.13 on 2025-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_userdetails',
            name='Test_status',
            field=models.CharField(default='Not_Started', max_length=25),
        ),
    ]
