# Generated by Django 4.1.13 on 2025-03-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_userdetails',
            old_name='Duration',
            new_name='Coding_duration',
        ),
        migrations.AddField(
            model_name='test_userdetails',
            name='MCQ_duration',
            field=models.IntegerField(default=0),
        ),
    ]
