# Generated by Django 4.1.13 on 2025-02-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitest', '0002_test_userdetails_test_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_userdetails',
            old_name='Collage',
            new_name='College',
        ),
    ]
