# Generated by Django 4.1.13 on 2025-03-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitest', '0003_trainer_details_test_userdetails_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_userdetails',
            name='Year',
            field=models.CharField(default='2024', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test_userdetails',
            name='batch',
            field=models.CharField(max_length=25),
        ),
    ]
