# Generated by Django 4.1.13 on 2025-02-20 10:50

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitest', '0003_rename_collage_test_userdetails_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_userdetails',
            name='Coding_Questions',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='test_userdetails',
            name='Coding_Questions_status',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
