# Generated by Django 4.1.13 on 2025-02-20 17:02

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitest', '0004_test_userdetails_coding_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetails_Days',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('Student_id', models.CharField(max_length=25)),
                ('Subject', models.CharField(max_length=25)),
                ('Attempts', models.IntegerField()),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Score', models.FloatField()),
                ('Qn', models.TextField(max_length=25)),
                ('Ans', models.TextField()),
                ('Result', djongo.models.fields.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='test_userdetails',
            name='Coding_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test_userdetails',
            name='Coding_Test_status',
            field=models.CharField(default='Not_Started', max_length=25),
        ),
    ]
