# Generated by Django 4.1.13 on 2025-02-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitest', '0005_questiondetails_days_test_userdetails_coding_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_userdetails',
            name='Duration',
            field=models.IntegerField(default=0),
        ),
    ]
