# Generated by Django 4.1.13 on 2025-02-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aptitest', '0006_test_userdetails_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_userdetails',
            name='Last_update',
            field=models.DateTimeField(default=None),
        ),
    ]
